#!/usr/bin/env python3
"""
スマート境界検出モジュールの情報
"""

print("=== スマート境界検出モジュール (transcription_smart_boundary.py) ===")
print("")
print("【概要】")
print("- 長時間動画を効率的に文字起こしするための特別なモジュール")
print("- 動画全体を一度に処理せず、賢く分割してメモリを節約")
print("")
print("【主な特徴】")
print("1. ターゲット分割時間: 20分")
print("   - 動画を約20分ごとに分割")
print("")
print("2. スマート境界検出:")
print("   - 単純に20分で切るのではなく、前後30秒の範囲で無音を探す")
print("   - 無音の中心を分割点にすることで、自然な切れ目で分割")
print("   - 無音が見つからない場合は、理想的な分割点をそのまま使用")
print("")
print("3. メモリ効率:")
print("   - 分割したい境界付近（前後30秒）のみをメモリに読み込んで無音検出")
print("   - 全体をメモリに読み込まないため、長時間動画でも処理可能")
print("")
print("【処理フロー】")
print("1. 動画の総時間を取得")
print("2. 20分ごとの理想的な分割点を計算")
print("3. 各分割点の前後30秒で無音を検出")
print("4. 最適な分割点を決定")
print("5. 各セグメント（分割された部分）を個別に文字起こし")
print("6. 結果を統合")
print("")
print("【使用方法】")
print("from core.transcription_smart_boundary import SmartBoundaryTranscriber")
print("transcriber = SmartBoundaryTranscriber(config)")
print("result = transcriber.transcribe(video_path)")
print("")
print("【パラメータ】")
print("- TARGET_DURATION = 20 * 60  # 20分ごとに分割")
print("- BOUNDARY_WINDOW = 30       # 境界前後30秒を検査")
print("- MIN_SILENCE_LEN = 0.5      # 最小無音長（0.5秒）")
print("- SILENCE_THRESH = -35       # 無音閾値（-35dB）")
print("")
print("【メリット】")
print("- メモリ使用量が大幅に削減される")
print("- 長時間動画（2時間以上）でも安定して処理可能")
print("- 自然な位置で分割されるため、文字起こしの精度も向上")
print("")
print("【注意点】")
print("- APIモードでは使用されない（ローカルモード専用）")
print("- 通常の文字起こしより少し時間がかかる場合がある")